baseURL = "https://thegreatwhiteshark.github.io/"
# baseURL = "/home/phil/git/thegreatwhiteshark.github.io/public"
languageCode = "en-us"
title = "theGreatWhiteShark blog"
theme = "casper"

[Params]
	tagline = "theGreatWhiteShark blog"
	author = "Philipp Müller"
	description = "A collection of all the my interests"
	github = "theGreatWhiteShark"
	logoBig = "/images/logo-big.jpg"
	logoSmall = "/images/logo-small.jpg" 
	email = "thetruephil@googlemail.com"
	hightlightJs = true
	credit = true
	customCSS = false

[[menu.main]]
	name = "About"
	url = "/#about"
	weight = 1
[[menu.main]]
	name = "Blogs"
	url = "/#blogs"
	weight = 2
[[menu.main]]
	name = "Projects"
	url = "/#projects"
	weight = 3
	
