# baseurl = "https://thegreatwhiteshark.github.io"
baseurl = "https://thegreatwhiteshark.github.io/thegreatwhiteshark.music.io/"
title = "theGreatWhiteShark"
languageCode = "en-us"
disqusshortname = "thegreatwhiteshark-music-io"
paginate = 7
pluralizelisttitles = false
theme = "casper"
RSSLink = "http://feeds.feedburner.com/Thegreatwhiteshark-music"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 200

[[menu.main]]
identifier = "linuxaudio"
name = "Linux audio"
pre = "<h3>Topics</h3>"
url = "/linux-audio"
weight = 115
[[menu.main]]
identifier = "musicprocessing"
name = "Music processing"
url = "/music-processing"
weight = 114
[[menu.main]]
identifier = "recording"
name = "Recording"
url = "/recording"
weight = 113

[[menu.main]]
name = "Github repos"
pre = "<h3>Follow me</h3>"
url = "https://github.com/theGreatWhiteShark"
weight = 100
[[menu.main]]
identifier = "blog"
name = "Blogs"
url = "https://thegreatwhiteshark.github.io/"
weight = 90
[[menu.main]]
identifier = "about"
name = "About me"
url = "/about"
weight = 80

[params]
authorwebsite = "https://thegreatwhiteshark.github.io/"
cover = "images/non-banner.png"
email = "thetruephil@googlemail.com"
description = "On a journey to find the perfect sound"
githubName = "theGreatWhiteShark"
hideHUGOSupport = false
pygmentsCodefences = true
pygmentsStyle = "monokai"
[permalinks]
post = "/:slug/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"
